---
resources:
- name: concourse-boot
  type: git
  source:
    uri: https://github.com/eiselems/concourseBoot.git
    branch: master

- name: my-timer
  type: time
  source:
    interval: 2m

jobs:
- name: test-and-package
  public: true
  serial: true
  plan:
  - get: concourse-boot
  - get: my-timer
    trigger: true
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: openjdk }

      inputs:
        - name: concourse-boot
      run:
        path: concourse-boot/ci/run-tests.sh
  - task: package-jar
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: openjdk }

      inputs:
        - name: concourse-boot
      run:
        path: cd concourse-boot && ./mvnw package